-- Generado por scripts/extraer-prototipo.mjs a partir del prototipo. No editar a mano.
-- 34 marcas; todas ocultas y sin beneficio salvo Shelby. Idempotente por nombre.
insert into public.marcas (orden, nombre, stand, beneficio, condiciones, creditos, codigo, clave, emblema, activa, logo_path) values
  (1, 'El Cafetín del Centro', '', '', '', 1, '9358', 'CAFETIN-QI', 'taza', false, 'semilla/el-cafetin-del-centro.jpg'),
  (2, 'Una Pausita Mendocina', 'Stand 56', '', '', 1, '8956', 'PAUSITA-SO', 'flor', false, 'semilla/una-pausita-mendocina.jpg'),
  (3, 'Enebro Gluten Free', '', '', '', 1, '6217', 'ENEBRO-YF', 'planta', false, 'semilla/enebro-gluten-free.jpg'),
  (4, 'Vicentica', '', '', '', 1, '8931', 'VICENTICA-3T', 'chemex', false, 'semilla/vicentica.jpg'),
  (5, 'Petit Patisserie', 'Stand 34', '', '', 1, '2734', 'PETIT-GQ', 'grano', false, 'semilla/petit-patisserie.jpg'),
  (6, 'Chiamo', 'Stand 33', '', '', 1, '5192', 'CHIAMO-9W', 'copa', false, 'semilla/chiamo.jpg'),
  (7, 'Cumbal', 'Stand 29', '', '', 1, '6813', 'CUMBAL-KZ', 'reloj', false, 'semilla/cumbal.jpg'),
  (8, 'Monte Tienda de Café', '', '', '', 1, '9343', 'MONTE-V1', 'jarra', false, 'semilla/monte-tienda-de-cafe.jpg'),
  (9, 'Chefsitos', '', '', '', 1, '7475', 'CHEFSITOS-IH', 'estrella', false, 'semilla/chefsitos.jpg'),
  (10, 'Crudo', '', '', '', 1, '7310', 'CRUDO-II', 'ondas', false, 'semilla/crudo.jpg'),
  (11, 'Shelby', 'Stand 8', '2x1 en café', 'En cualquier café de la carta. Uno por vez.', 2, '2870', 'SHELBY-JM', 'taza', true, 'semilla/shelby.jpg'),
  (12, 'Hefesto', '', '', '', 1, '1255', 'HEFESTO-FX', 'flor', false, 'semilla/hefesto.jpg'),
  (13, 'Pato Coffee', '', '', '', 1, '7979', 'PATO-P5', 'planta', false, 'semilla/pato-coffee.jpg'),
  (14, 'Alma Cacao', '', '', '', 1, '2709', 'ALMA-5V', 'chemex', false, 'semilla/alma-cacao.jpg'),
  (15, 'Carpediem', '', '', '', 1, '9133', 'CARPEDIEM-4Z', 'grano', false, 'semilla/carpediem.jpg'),
  (16, 'Marian Estudio', '', '', '', 1, '8452', 'MARIAN-3K', 'copa', false, 'semilla/marian-estudio.jpg'),
  (17, 'Duende Negro', '', '', '', 1, '2345', 'DUENDE-4N', 'reloj', false, 'semilla/duende-negro.jpg'),
  (18, 'Pepper Truck', '', '', '', 1, '6618', 'PEPPER-GE', 'jarra', false, 'semilla/pepper-truck.jpg'),
  (19, 'Cono Creps', '', '', '', 1, '8227', 'CONO-X5', 'estrella', false, 'semilla/cono-creps.jpg'),
  (20, 'Helados Verde Pistacchio', '', '', '', 1, '7662', 'VERDE-GY', 'ondas', false, 'semilla/helados-verde-pistacchio.jpg'),
  (21, 'Mates Marcán', 'Isla 1', '', '', 1, '5219', 'MATES-JT', 'taza', false, 'semilla/mates-marcan.jpg'),
  (22, 'Belén Berti Tattoo', 'Isla 2', '', '', 1, '9294', 'BELEN-DM', 'flor', false, 'semilla/belen-berti-tattoo.jpg'),
  (23, 'Pintao Pins', 'Isla 3', '', '', 1, '8668', 'PINTAO-IW', 'planta', false, 'semilla/pintao-pins.jpg'),
  (24, 'La Cabaña Chocolates', 'Isla 4', '', '', 1, '6812', 'CABANA-EW', 'chemex', false, 'semilla/la-cabana-chocolates.jpg'),
  (25, 'Chocolates Hipólito', 'Isla 5 · entrada', '', '', 1, '2394', 'HIPOLITO-SM', 'grano', false, 'semilla/chocolates-hipolito.jpg'),
  (26, 'India & Co.', 'Sponsor', '', '', 1, '8442', 'INDIA-7Y', 'copa', false, 'semilla/india-co.jpg'),
  (27, 'Reserva del Sol', 'Sponsor', '', '', 1, '4656', 'RESERVA-NW', 'reloj', false, 'semilla/reserva-del-sol.jpg'),
  (28, 'Cata Internacional', 'Sponsor', '', '', 1, '8027', 'CATA-4H', 'jarra', false, 'semilla/cata-internacional.jpg'),
  (29, 'Banquetes Suárez', 'Sponsor', '', '', 1, '3173', 'BANQUETES-XN', 'estrella', false, 'semilla/banquetes-suarez.jpg'),
  (30, 'Waggon', '', '', '', 1, '3450', 'WAGGON-32', 'ondas', false, null),
  (31, 'Manga', '', '', '', 1, '3685', 'MANGA-PN', 'taza', false, null),
  (32, 'Tregar', '', '', '', 1, '8196', 'TREGAR-RC', 'flor', false, null),
  (33, 'Macanudo', '', '', '', 1, '9925', 'MACANUDO-83', 'planta', false, null),
  (34, 'Tercer Mundo', '', '', '', 1, '2685', 'TERCER-NF', 'chemex', false, null)
on conflict (nombre) do nothing;
